## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp" ## "/home/pervinco/Datasets/BKAI_FAKE"
save_dir: "./runs"
train: "train"
valid: "valid"
test: "test"
weight_dir: ""

## hyp-params
num_classes: 3
model: "segformer"
epochs: 100
img_size: 512
batch_size: 8
init_lr: 0.0001
gamma: 2

## augmentation
spatial_alpha: 0.45 ## 0.45