## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
background_dir: "/home/pervinco/Datasets/background/train/1_ulcerative_colitis"
weight_dir: ""
save_dir: "./runs"
train: "train"
valid: "valid"
test: "test"

## hyp-params
num_classes: 3
model: "segformer"
epochs: 300
img_size: 512
batch_size: 8
init_lr: 0.0001

alpha: null ## [0.006248079459464449, 0.867032189947176, 0.12671973059335967]
gamma: 2

## augmentation
spatial_alpha: 0.45 ## 0.45